<!DOCTYPE html>
<html lang="en" data-theme="dark"><head>
    <title>TPL and Error Handling | David Haney</title>	
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-PR2HVYP6QG"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());
	  gtag('config', 'G-PR2HVYP6QG');
	</script>
    
    <meta charset="utf-8"><meta name="generator" content="Hugo 0.78.1" /><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
    <meta name="description" content="Programmer / Engineering Manager">
    
    <link rel="stylesheet"
          href="https://www.davidhaney.io/css/style.min.2b188541d728e8afd69a6f1b8b83f89f2b138d671fb728eff20ff3f3dcf5b55e.css"
          integrity="sha256-KxiFQdco6K/Wmm8bi4P4nysTjWcftyjv8g/z89z1tV4="
          crossorigin="anonymous"
          type="text/css">
    <link rel="stylesheet"
          href="https://www.davidhaney.io/css/syntax.21cc1ccec065ce1e0f94f7a6a5a26cb58c9044e659b5010305c81fe0a1d47029.css"
          crossorigin="anonymous"
          type="text/css">
    <link rel="stylesheet"
          href="https://www.davidhaney.io/css/custom.fae948156e332ca3bf68a701055b56de9a9e50933e7a49250b7cee83f7ed8464.css"
          crossorigin="anonymous"
          type="text/css"><link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" 
    integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" 
    crossorigin="anonymous" />

    
    <link rel="shortcut icon" href="https://www.davidhaney.io/favicons/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="https://www.davidhaney.io/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://www.davidhaney.io/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://www.davidhaney.io/favicons/favicon-16x16.png">

    <link rel="canonical" href="https://www.davidhaney.io/tpl-and-error-handling/">

    
    
    
    
    <script type="text/javascript"
            src="https://www.davidhaney.io/js/anatole-header.min.e782db136ec18d105a4552702eac49f4620d6867da3fbf808bd53e806c96be6e.js"
            integrity="sha256-54LbE27BjRBaRVJwLqxJ9GINaGfaP7&#43;Ai9U&#43;gGyWvm4="
            crossorigin="anonymous"></script>
    <meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="https://www.davidhaney.io/img/opengraph.png"/>

<meta name="twitter:title" content="TPL and Error Handling"/>
<meta name="twitter:description" content="As of .NET 4.0, the TPL or Task Parallel Library is king when it comes to parallelization. It allows for smooth, easy multi-threading for any application. There is a slight learning curve, however, and a major part of this is understanding how Exceptions bubble-up while using the TPL."/>

</head>
<body><div class="sidebar animated fadeInDown">
    <div class="logo-title">
        <div class="title">
            <img src="https://www.davidhaney.io/img/me.jpg" alt="profile picture">
            <h3 title=""><a href="/">David Haney</a></h3>
            <div class="description">
                <p>Programmer / Engineering Manager</p>
            </div>
        </div>
    </div>
    <ul class="social-links">
        
            <li>
                <a href="https://www.github.com/haneytron" rel="me" aria-label="GitHub">
                    <i class="fab fa-github fa-2x" aria-hidden="true"></i>
                </a>
            </li>
        
            <li>
                <a href="https://www.twitter.com/haneytron" rel="me" aria-label="Twitter">
                    <i class="fab fa-twitter fa-2x" aria-hidden="true"></i>
                </a>
            </li>
        
            <li>
                <a href="https://www.linkedin.com/in/davidahaney" rel="me" aria-label="Linkedin">
                    <i class="fab fa-linkedin fa-2x" aria-hidden="true"></i>
                </a>
            </li>
        
    </ul>
    <div class="footer">
        <div class="by_farbox">&copy; David Haney 2020 </div>
    </div>
</div>
<div class="main">
    <div class="page-top animated fadeInDown">
    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
    </a>
    <ul class="nav" id="navMenu">
        
        
            
            <li><a 
                   href="/"
                        
                   title="">Home</a></li>
        
            
            <li><a 
                   href="/post/"
                        
                   title="">Posts</a></li>
        
            
            <li><a 
                   href="/tags/"
                        
                   title="">Tags</a></li>
        
        
        <li class="theme-switch-item">
            <a class="theme-switch" title="Switch Theme">
                <i class="fa fa-adjust fa-fw" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</div>

    <div class="autopagerize_page_element">
        <div class="content">
    <div class="post animated fadeInDown">
        <div class="post-content">

            <div class="post-title">
                <h3>TPL and Error Handling</h3>
                
                    <div class="info">
                        <em class="fa fa-sun-o"></em>
                        <span class="date">Sun, Aug 5, 2012</span>
                        <em class="fa fa-clock-o"></em>
                        <span class="reading-time">5-minute read</span>
                    </div>
                
            </div>

            <p>As of .NET 4.0, the TPL or Task Parallel Library is king when it comes to parallelization. It allows for smooth, easy multi-threading for any application. There is a slight learning curve, however, and a major part of this is understanding how Exceptions bubble-up while using the TPL.</p>
<p>Let’s partake in a simple example. This code will create and run a task that throws an Exception, and then attempt to catch it:</p>
<pre><code>static void Main(string[] args)
{
    try
    {
        // Initialize a Task which throws exception
        var task = new Task(() =&gt;
        {
            throw new Exception(&quot;Task broke!&quot;);
        });
        // Start the Task
        task.Start();
    }
    // Attempt to catch the Task Exception
    catch (Exception ex)
    {
        Console.WriteLine(&quot;Caught the TPL exception&quot;);
    }

    Console.WriteLine(&quot;End of method reached&quot;);
    Console.ReadKey();
}
</code></pre>
<p>When we run it, we get this result:</p>
<figure>
    <img src="/img/tpl-and-error-handling-first-output.png"/> <figcaption>
            <h4>The Output</h4>
        </figcaption>
</figure>

<p>The Exception was not caught. This is because the Task is run on a different thread, which has its own Stack memory and execution path, which consists of the code inside of the Task and not much else. As a result, when the Task is run, the flow of control returns to the next line in our application, unaware of the Task or its outcome. Once the Exception in the Task is thrown, it is thrown in a different scope, effectively outside of our Main method. It’s almost as if we ran an entirely different application, but attempted to catch its Exception in this application. This just won’t work.</p>
<p>There is a way to work around this however. One interesting thing about the TPL is the <!-- raw HTML omitted -->Task.WaitAll<!-- raw HTML omitted --> method. It allows the control of flow of your executing Tasks/threads to return to your calling method. By adding this method to our code, we can make our main thread stall until the Task completes, which also enables it to catch the Task’s exception:</p>
<pre><code>static void Main(string[] args)
{
    try
    {
        // Initialize a Task which throws exception
        var task = new Task(() =&gt;
        {
            throw new Exception(&quot;Task broke!&quot;);
        });
        // Start the Task
        task.Start();
        // Wait for the Task to complete, thus keeping control of flow
        Task.WaitAll(task);
    }
    // Attempt to catch the Task Exception
    catch (Exception ex)
    {
        Console.WriteLine(&quot;Caught the TPL exception&quot;);
    }

    Console.WriteLine(&quot;End of method reached&quot;);
    Console.ReadKey();
}
</code></pre>
<p>The output is as follows:</p>
<figure>
    <img src="/img/tpl-and-error-handling-second-output.png"/> <figcaption>
            <h4>Second Output</h4>
        </figcaption>
</figure>

<p>This time we were able to catch the Exception. Of note, the Exception which is thrown by Tasks is typically the <!-- raw HTML omitted -->AggregateException<!-- raw HTML omitted --> which allows you to catch multiple, often asynchronous Exceptions as one Exception (which is easier for a single thread to handle). A quick demo of this functionality (let’s have 5 threads each throw an Exception):</p>
<pre><code>static void Main(string[] args)
{
    try
    {
        // A List of Tasks
        var taskList = new List&lt;Task&gt;(5);

        for (int i = 0; i &lt; 5; i++)
        {
            // Initialize a Task which throws exception
            var task = new Task(() =&gt;
            {
                throw new Exception(&quot;It broke!&quot;);
            });
            // Start the Task
            task.Start();
            // Add to List
            taskList.Add(task);
        }
        // Wait for all Tasks to complete, thus keeping control of flow
        Task.WaitAll(taskList.ToArray());
    }
    // Attempt to catch the Task Exception
    catch (AggregateException agex)
    {
        Console.WriteLine(&quot;Caught the TPL exception(s)&quot;);
        // Output all actual Exceptions
        foreach (var ex in agex.InnerExceptions)
        {
            Console.WriteLine(ex.Message);
        }
    }

    Console.WriteLine(&quot;End of method reached&quot;);
    Console.ReadKey();
}
</code></pre>
<p>And the output:</p>
<figure>
    <img src="/img/tpl-and-error-handling-third-output.png"/> <figcaption>
            <h4>Third Output</h4>
        </figcaption>
</figure>

<p>So as you can see, there are ways to handle Tasks throwing Exceptions, <em>if you have your calling thread pause and wait for the Tasks to complete</em>. This, of course, is not always practical so your other option is to handle the exception within the Task’s scope – just like you would with regular, single-threaded code. In effect you treat the code within the Task as isolated, single-threaded code, and catch and handle Exceptions accordingly. A slight mod to our application will show you this:</p>
<pre><code>static void Main(string[] args)
{
    for (int i = 0; i &lt; 5; i++)
    {
        // Initialize a Task which throws exception
        var task = new Task(() =&gt;
        {
            try
            {
                throw new Exception(&quot;It broke!&quot;);
            }
            catch (Exception ex)
            {
                // Output the Exception
                Console.WriteLine(ex.Message);
            }
        });
        // Start the Task
        task.Start();
        // Note: no longer waiting for Task to finish
    }

    Console.WriteLine(&quot;End of method reached&quot;);
    Console.ReadKey();
}
</code></pre>
<p>And the result of this change:</p>
<figure>
    <img src="/img/tpl-and-error-handling-fourth-output.png"/> <figcaption>
            <h4>Fourth Output</h4>
        </figcaption>
</figure>

<p>Note the interesting results of this. Our main thread did not wait for the Tasks to complete, and so it the Task results were never returned back to the calling thread’s flow of control. As a result, the “End of method reached” text actually came <em>before</em> the threads crashed, because it happened sooner.</p>
<p>Note also that only 4 of the 5 Exceptions were written to the Console. This is due to a race condition in your parallelized application: The Console is a single/static reference and so our 5 spawned threads plus 1 main thread all race to output to it. In this particular instance of the application being run, the Console.ReadKey method was executed after the first 4 Tasks had written their output, but before the 5th Task wrote its output. This does not mean that it was not handled; it simply means that, in a way that is classic to multi-threaded applications, we encountered a race condition. I ran this application another 10 or 20 times and saw many variations: sometimes 3 Exceptions were output, sometimes 4, and rarely all 5. This is a great example of a race condition within an application, and one which you could handle using the above strategy of Task.WaitAll prior to outputting your final Console.ReadKey statement and terminating your application.</p>
<p>It’s up to you individually to decide which style of TPL error handling makes the most sense in each application. It depends on the purpose of each thread and the implications of having your application wait for threads to complete, considered on a per-application basis.</p>
<p>One final note is that other parallel operations, such as <!-- raw HTML omitted -->Parallel.ForEach<!-- raw HTML omitted --> and <!-- raw HTML omitted -->Parallel LINQ (PLINQ)<!-- raw HTML omitted --> use <!-- raw HTML omitted -->AggregateException<!-- raw HTML omitted --> as well to catch their thrown Exceptions, and that the AggregateException offers a <!-- raw HTML omitted -->Flatten method<!-- raw HTML omitted --> for re-throwing nested AggregateExceptions as a one-level deep single AggregateException to simplify handling of them.</p>

        </div>
        <div class="post-footer">
            <div class="info">
                <span class="separator"><a class="category" href="/categories/blog/">blog</a></span>

                <span class="separator"><a class="tag" href="/tags/dotnet/">dotnet</a><a class="tag" href="/tags/async/">async</a><a class="tag" href="/tags/csharp/">csharp</a><a class="tag" href="/tags/performance/">performance</a><a class="tag" href="/tags/programming/">programming</a><a class="tag" href="/tags/tasks/">tasks</a><a class="tag" href="/tags/tpl/">tpl</a></span>

            </div>
        </div>

        
            <div id="fb_comments_container">
                    <h2>comments</h2>
                    <div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "haney" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
                </div>
        
    </div>


        </div>
    </div>
</div>

<script type="text/javascript"
        src="https://www.davidhaney.io/js/jquery.min.86b1e8f819ee2d9099a783e50b49dff24282545fc40773861f9126b921532e4c.js"
        integrity="sha256-hrHo&#43;BnuLZCZp4PlC0nf8kKCVF/EB3OGH5EmuSFTLkw="
        crossorigin="anonymous"></script>




<script type="text/javascript"
        src="https://www.davidhaney.io/js/bundle.min.0f9c74cb78f13d1f15f33daff4037c70354f98acfbb97a6f61708966675c3cae.js"
        integrity="sha256-D5x0y3jxPR8V8z2v9AN8cDVPmKz7uXpvYXCJZmdcPK4="
        crossorigin="anonymous"></script>

<script type="text/javascript"
        src="https://www.davidhaney.io/js/medium-zoom.min.92f21c856129f84aeb719459b3e6ac621a3032fd7b180a18c04e1d12083f8aba.js"
        integrity="sha256-kvIchWEp&#43;ErrcZRZs&#43;asYhowMv17GAoYwE4dEgg/iro="
        crossorigin="anonymous"></script>
</body>

</html>
